#!/bin/bash
set failed=""
set passed=""
for x in G_* ; do
  want_group="$(echo $x | sed -e 's/G_//')"
  got_group="$(../symmetry.x -verbose -1 "$x" | awk '/It seems to be the .* point group/{print $6}')"
  # echo "For the $want_group geometry I got $got_group"
  if [ "$want_group" != "$got_group" ] ; then
    failed="$failed $want_group"
  else
    passed="$passed $want_group"
  fi
done
[ ! -z "$passed" ] && echo "Tests passed: $passed"
[ ! -z "$failed" ] && echo "Tests failed: $failed"
exit $([ -z "$failed" ])
